- name: install java
  ansible.builtin.dnf:
    name:
      - java-17-openjdk
      - fontconfig
    state: present

- name: Add jenkins user
  ansible.builtin.user:
    name: jenkins

- name: create jenkins folder
  ansible.builtin.file:
    path: /jenkins
    owner: jenkins
    group: jenkins
    state: directory
